---
contentdir: "content"
layoutdir: "layouts"
publishdir: ""
theme: “hyde-x”
indexes:
  category: "categories"
  page: "pages"
  vita: “vitas”
baseurl: "http://jlopezsi.github.io/“
title: “Jordi’s Blog Template for GitHub Pages"
params:
  ProfilePicture: "pathOrUrlToImage"
  links:
    Name:  “Jordi López“
    Email: “jordi.lopez@uab.es”
    Twiter: “jlopezsi”
...
